### ISSUE TITLE
Hard coded user path

### ISSUE THREAD

**Issue by junhaoliao** [t-lin/ryu_ofctl#1]
Hi Thomas. Although I am not sure if this is the best place to post the issue, but it's probably the fastest way I can contact you.

When I was trying to migrate the ECE361 scripts and binaries from the given VM image to my local machine, I found the user path in "ece361-update" was hard-coded to "/home/ubuntu/ryu". It happens that my user name is not ubuntu... I tried modifying the script directly(changed to "/$HOME/ryu"), but there seems to be some command updating and overwriting the script. 

Anyways, I have copied the ryu directory to /home/ubuntu/ and things seem to be working perfectly. However, I am not sure about other functionalities not used in Lab 1. Do you recommend us to stick with the given VM image?

Regards

**Comment by t-lin** [comment]
Hi Junhao, the new labs this year were designed to use the VM as the main front-end environment. There's likely other environment settings and paths in the ece361-* scripts that are hard-coded as well. So yes, I do recommend just using the VM image provided for doing the labs, as all my development and testing were done within the VM.

**Comment by junhaoliao** [comment]
Thanks for the clarification! I will do the future labs in the VM.





Regards,



Junhao


Computer Engineering Student

University of Toronto

Website: https://junhao.cahttps://junhao.ca

Phone: 778-953-3993






---- On Sun, 19 Jan 2020 16:00:41 -0500 Thomas Lin <notifications@github.com> wrote ----



Hi Junhao, the new labs this year were designed to use the VM as the main front-end environment. There's likely other environment settings and paths in the ece361-* scripts that are hard-coded as well. So yes, I do recommend just using the VM image provided for doing the labs, as all my development and testing were done within the VM.
